[GH-51]feature/add-timestamped-speaker-turns
CouncilDataProject/seattle_v2 pull request #57
Opened 2020-01-05 02:12 UTC by tohuynh

**Pull request recommendations:**
- [x] Name your pull request _your-development-type/short-description_. Ex: _feature/read-tiff-files_
- [x] Link to any relevant issue in the PR description. Ex: _Resolves [gh-12], adds tiff file format support_
#51. And also #49, where the feature to jump to transcript portion from `videoTimePoint` was requested.
- [x] Provide context of changes.
Add UI changes to show `timestamped-speaker-turns`.
I ran into a little block trying to add the jump to transcript portion feature. Unfortunately I couldn't use that "card" UI for each speaker-turn. Instead I have a horizontal divider with `speaker` at the top of each speaker-turn. Also I used `New Speaker` for empty string speaker as requested.
Here's what it looks like:
![image](https://user-images.githubusercontent.com/37560480/71774007-094f4080-2f1c-11ea-9afe-f77fe9ca5515.png)
- [x] Provide relevant tests for your feature or bug fix.
- [x] Provide or update documentation for any feature added by your pull request.

Thanks for contributing!

2020-01-05 02:18 UTC, tohuynh commented on src/components/EventTranscript.jsx
> +  "@media(min-width:1000px)": {
Just changed it to min-width instead max-width. The break point is essentially the same.

2020-01-05 03:58 UTC, JacksonMaxfield commented
Before I review, how did you test this without any speaker turns transcripts existing in the database?

2020-01-05 04:25 UTC, evamaxfield requested changes
First, I just want to again say, excellent documentation and comments. It makes it so easy to fly through these PRs.

Tested on Chrome and Firefox, when entering the page with a timestamp, the video jumps to the time correctly and the transcript tab is selected by the page doesn't jump to that transcript block. This was tested with the current transcripts, not the `speaker-blocks` transcripts.

2020-01-05 04:25 UTC, JacksonMaxfield commented on src/components/EventTranscript.jsx
> +};
Smart!

2020-01-05 04:28 UTC, JacksonMaxfield commented on src/components/Event.jsx
> +
This is fine for now. In the future this, all other `"speaker-turns"` strings should probably converted to a constants variable like the one in `cdptools.sr_models.constants.TranscriptFormats`. It is safer to have a single place for the string to live than for that string to be used all over the place and I can imagine where this string keeps getting used more and more.

2020-01-05 04:31 UTC, tohuynh commented on src/components/Event.jsx
> +
> First, I just want to again say, excellent documentation and comments. It makes it so easy to fly through these PRs.
> 
> Tested on Chrome and Firefox, when entering the page with a timestamp, the video jumps to the time correctly and the transcript tab is selected by the page doesn't jump to that transcript block. This was tested with the current transcripts, not the `speaker-blocks` transcripts.

Which event and what time point?

2020-01-05 04:32 UTC, JacksonMaxfield commented
Also from the changes, am I assuming correctly that the same code is used for scrolling to position as is the EventTranscriptSearch? So when you click on a result in the Event Transcript Search it will also scroll to that position in the full transcript as well?

2020-01-05 04:40 UTC, tohuynh commented
> Also from the changes, am I assuming correctly that the same code is used for scrolling to position as is the EventTranscriptSearch? So when you click on a result in the Event Transcript Search it will also scroll to that position in the full transcript as well?

I'm not following the question. There is no automatic scrolling in EventTranscriptSearch. It just renders the sentences that contains the `searchText`.

2020-01-05 04:41 UTC, JacksonMaxfield commented on src/components/Event.jsx
> +
http://localhost:3000/#/events/3cc29b7a-9df7-467b-b7a2-e6a546d1984c?t=1612

Really any event at any timepoint I tested.

2020-01-05 04:43 UTC, JacksonMaxfield commented
> > Also from the changes, am I assuming correctly that the same code is used for scrolling to position as is the EventTranscriptSearch? So when you click on a result in the Event Transcript Search it will also scroll to that position in the full transcript as well?
> 
> I'm not following the question. There is no automatic scrolling in EventTranscriptSearch. It just renders the sentences that contains the `searchText`.

Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?

2020-01-05 04:45 UTC, tohuynh commented on src/components/Event.jsx
> +
> This is fine for now. In the future this, all other `"speaker-turns"` strings should probably converted to a constants variable like the one in `cdptools.sr_models.constants.TranscriptFormats`. It is safer to have a single place for the string to live than for that string to be used all over the place and I can imagine where this string keeps getting used more and more.

I agree. How

> > > Also from the changes, am I assuming correctly that the same code is used for scrolling to position as is the EventTranscriptSearch? So when you click on a result in the Event Transcript Search it will also scroll to that position in the full transcript as well?
> > 
> > 
> > I'm not following the question. There is no automatic scrolling in EventTranscriptSearch. It just renders the sentences that contains the `searchText`.
> 
> Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?

Oh, do you mean `onclick` of the play button EventTranscriptSearch?

2020-01-05 04:47 UTC, tohuynh commented
> Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?

Oh do you mean the `onclick` of the play button?

2020-01-05 04:48 UTC, JacksonMaxfield commented
> > Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?
> 
> Oh do you mean the `onclick` of the play button?

Yep!

Sidenote: GitHub should really look into a thread system for conversations.

2020-01-05 04:53 UTC, tohuynh commented
> > > Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?
> > 
> > 
> > Oh do you mean the `onclick` of the play button?
> 
> Yep!
> 
> Sidenote: GitHub should really look into a thread system for conversations.



> > > Right but the `onclick` of any of the results, does that `onclick` now also scroll to the full transcript position of that clicked result?
> > 
> > 
> > Oh do you mean the `onclick` of the play button?
> 
> Yep!
> 
> Sidenote: GitHub should really look into a thread system for conversations.
No, it doesn't do that right now.
That's a good idea. This can be done I think through sending a custom-event
and have EventTranscript listen for that event and then scroll to right portion.

2020-01-06 03:08 UTC, tohuynh commented
New changes removed react-virtualized components from EventTranscript
and uses element.scrollIntoView to do the scrolling.

2020-01-06 22:52 UTC, evamaxfield approved these changes
Looks great! Thanks again for all the work on this and sorry for going back and forth on the jump to timepoint in transcript.

2020-01-06 22:52 UTC, merged